@startuml
title Блок-схема рисования домика

start
:Создание нового изображения;
:Определение размеров изображения;

:Рисование крыши домика;
:Рисование фасада домика;

:Рисование забора;
:Добавление столбиков забора;
:Добавление плит забора;

:Добавление текста "HOUSE";
:Поворот текста на 180 градусов;

:Сохранение изображения на диск;
stop
@enduml